version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: always
  redis:
    image: redis:alpine
    restart: always
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-nestdb}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    volumes:
      - dbdata:/data/postgres
    ports:
      - 5432:5432
    networks:
      - node-network
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/root/.pgadmin
    depends_on:
      - postgres
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - node-network

volumes:
  dbdata:
  pgadmin:
  node_modules:

networks:
  node-network:
    driver: bridge
